# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Shape' do
pod 'AFNetworking', '~> 2.6.1'
pod 'MJExtension', '~> 2.5.12'
pod 'SDWebImage', '~> 3.7.3'
pod 'Masonry', '~> 0.6.3'
pod 'MBProgressHUD'
pod 'MagicalRecord', '~> 2.3.0'
pod 'MJRefresh'
end

