# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MintcodeIM' do

pod 'AFNetworking', '~> 3.0.4' #'~> 2.5.4'
pod 'MJExtension', '~> 3.0.10' #'~> 2.5.2'
pod 'FMDB', '~> 2.6' #'~> 2.5'
pod 'SocketRocket', '~> 0.4.2'
pod 'DateTools', '~> 1.7.0'
pod 'Reachability', '~> 3.2'

end

