# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry', '~> 1.0.1'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 3.8.1'
pod 'DateTools', '~> 1.7.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'AlipaySDK-2.0', '~> 15.0.2'
pod 'FMDB', '~> 2.6'
pod 'SocketRocket', '~> 0.5.1'
pod 'Reachability', '~> 3.2'
pod 'MWPhotoBrowser-ADS', '~> 1.0.0'
pod 'TTTAttributedLabel', '~> 2.0.0'
pod 'SVWebViewController', '~> 1.0'

pod 'DZNEmptyDataSet', '~> 1.8.1'

pod 'UMengAnalytics-NO-IDFA'

target 'HMClient' do

end

target 'HMClient_外网正式' do
    
end

target 'HMClient_仿真' do
    
end

target 'UserLoginTests' do
    
end

