# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 1.0.0'
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'FMDB', '~> 2.6'
pod 'SocketRocket', '~> 0.4.2'
pod 'DateTools', '~> 1.7.0'
pod 'Reachability', '~> 3.2'
pod 'MWPhotoBrowser-ADS', '~> 1.0.0'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'SVWebViewController', '~> 1.0'
pod 'IQKeyboardManager', '~> 4.0.1'
pod 'MJRefresh', '~> 3.1.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'pop', '~> 1.0'

target 'HMDoctor' do
pod 'UMengAnalytics-NO-IDFA', '~> 4.1.9'
end

target 'HMDoctor外网正式' do
pod 'UMengAnalytics-NO-IDFA', '~> 4.1.9'
end

target 'HMDoctor仿真环境' do
pod 'UMengAnalytics-NO-IDFA', '~> 4.1.9'
end


target 'DetectWarnningTests' do
    
end
